### ISSUE TITLE
最新版に更新できない

### ISSUE THREAD

**Issue by kensakamoto** [tanakaht/easyautotrans#10]
git hub上のコードが変更された際に、それをpullして、python setup.pyをしても、正常に動きません。どうすれば良いのでしょうか？

**Comment by nagatea** [comment]
どんなエラーが出るんですか？(それとも動くけど最新版に更新できない感じですか？)

**Comment by kensakamoto** [comment]
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: no commands supplied

python setup.pyを実行する前に、pip instal ~をしてもダメでした
